baseURL = "https://editadapt.net/"
languageCode = "fr"
title = "éditadapt"
subtitle = ""
#theme = "terrassa"

theme = "zen"

DefaultContentLanguage = "fr"
copyright = "GPL"

[languages]
  [languages.es]
    title = "Servicios para édiciòn inclusiva y adaptada"
    languageName = "Español"
    contentDir = "content/es"
    weight = 1
  [languages.en]
    title = "Services for inclusive and specialized publishing"
    languageName = "English"
    contentDir = "content/en"
    weight = 2
  [languages.fr]
    title = "Services pour l'édition inclusive et adaptée"
    languageName = "Français"
    contentDir = "content/fr"
    weight = 3

